(defstruct humanoid
  #|SFVec3f|# (     bbox-center             '(0 0 0))
  #|SFVec3f|# (     bbox-size               '(-1 -1 -1))
  #|SFVec3f|# (     center                 '(0 0 0))
  #|MFString|# (    info                   nil)
  #|MFNode|# (      joints                 nil)
  #|SFString|# (    name                   "" :type string)
  #|SFRotation|# (  rotation               '(0 0 1 0))
  #|SFVec3f|# (     scale                  '(1 1 1))
  #|SFRotation|# (  scale-orientation       '(0 0 1 0))
  #|MFNode|# (      segments       nil)
  #|MFNode|# (      sites          nil)
  #|MFNode|# (      skeleton       nil)
  #|MFNode|# (      skin           nil)
  #|SFNode|# (      skin-coord     nil)
  #|SFNode|# (      skin-normal    nil)
  #|SFVec3f|# (     translation    '(0 0 0))
  #|SFString|# (    version  "2.0" :type string)
  #|MFNode|# (      viewpoints     nil)
  )

(defstruct Joint
  #|SFVec3f|# (      center              '(0 0 0))
  #|MFNode|# (       children            nil)
  #|MFFloat|# (      llimit              nil)
  #|SFRotation|# (   limit-orientation    '(0 0 1 0))
  #|SFString|# (     name                "" :type string)
  #|SFRotation|# (   rotation            '(0 0 1 0))
  #|SFVec3f|# (      scale               '(1 1 1))
  #|SFRotation|# (   scale-orientation    '(0 0 1 0))
  #|MFInt32|# (      skin-coord-Index      nil)
  #|MFFloat|# (      skin-coord-Weight     nil)
  #|MFFloat|# (      stiffness           '(0 0 0))
  #|SFVec3f|# (      translation         '(0 0 0))
  #|MFFloat|# (      ulimit              nil)
  )

(defstruct Segment
  #|SFVec3f|# (      bbox-Center        '(0 0 0))
  #|SFVec3f|# (      bbox-Size          '(-1 -1 -1))
  #|SFVec3f|# (      center-Of-Mass      '(0 0 0))
  #|MFNode|# (       children          nil)
  #|SFNode|# (       coord             nil)
  #|MFNode|# (       displacers        nil)
  #|SFFloat|# (      mass              -1)
  #|MFFloat|# (      moments-Of-Inertia  '((0 0 0)
                                         (0 0 0)
                                         (0 0 0)))
  #|SFString|# (     name              "" :type string)
  )

(defstruct Site
  #|SFVec3f|# (      center            '(0 0 0))
  #|MFNode|# (       children          nil)
  #|SFString|# (     name              "" :type string)
  #|SFRotation|# (   rotation          '(0 0 1 0))
  #|SFVec3f|# (      scale             '(1 1 1))
  #|SFRotation|# (   scale-orientation  '(0 0 1 0))
  #|SFVec3f|# (      translation       '(0 0 0))
  )

(defstruct displacer
  #|MFInt32|# (  coord-Index     nil)
  #|MFVec3f|#  ( displacements  nil)
  #|SFString|# ( name           "" :type string)
  #|SFFloat|#  ( weight         0.0 :type float)
  )

